### ISSUE TITLE
the config file save is error.

### ISSUE THREAD

**Issue by gonboy** [ltcmelo/uaiso-plugins#3]
This is a great project.
Expect more perfect
－－－－－－－－－－－－－－－－－－－－－－－－error
the config file save is error.
because:
**Save:**( for (auto const& option : m_options))  size=4
[UaisoSettingsHaskell]
[UaisoSettingsPython]
[UaisoSettingsGo]
[UaisoSettingsD]

**Load:(**for (auto lang : availableLangs())) only size=3
[UaisoSettingsPython]
[UaisoSettingsGo]
[UaisoSettingsD]

and I think this code does not have much effect   “**m_prevIndex**”

－－－－－－－－－－－－－－－－－－－－－－fix

So I change It, hope you can fix it.
1. remove all  " m_prevIndex "
2. //by gonboy(change slot)

``` c++
connect(m_d->m_page->langCombo, SIGNAL(currentIndexChanged(int)),
              this, SLOT(settingsToUI()));
```

3.
//by gonboy.（ new function ）

``` C++
int UaisoSettingsPage::langName2Id(QString name)
{
    for (auto lang : availableLangs())
    {
        if(name == QString::fromStdString(langName(lang)))
            return static_cast<int>(lang);
    }
    return -1;
}

void UaisoSettingsPage::settingsFromUI()
{
    int id = langName2Id(m_d->m_page->langCombo->currentText());
    if(id >= 0)
        updateOptionsOfLang(id);
    else
    {
        qDebug() << "settingsFromUI failed";
    }
}

void UaisoSettingsPage::settingsToUI()
{
    int id = langName2Id(m_d->m_page->langCombo->currentText());
    if(id >=0)
        displayOptionsForLang(id);
    else
    {
        qDebug() << "settingsToUI failed";
    }
}
```

**Comment by ltcmelo** [comment]
I forgot to mention this here. The issue was actually in Uaiso itself. I added the Haskell language name but forgot to add a corresponding enumerator id. Thanks for pointing out.
