### ISSUE TITLE
END_NUM_LIT' was not declared

### ISSUE THREAD

**Issue by kaarrot** [ltcmelo/uaiso-plugins#4]
When building the plugin I get the following error:

```
In file included from ../uaisoeditor.cpp:64:0:
/home/kuba/SRC/uaiso/Parsing/TokenCategory.h: In function 'bool uaiso::isNumLit(uaiso::Token)':
/home/kuba/SRC/uaiso/Parsing/TokenCategory.h:50:39: error: 'END_NUM_LIT' was not declared in this scope
     return tk > BEGIN_NUM_LIT && tk < END_NUM_LIT;
```

Currently I'm on more recent version of  QtCreator (3.6.82) Do you think this may be related?

**Comment by kaarrot** [comment]
Is it possible this has been renamed to END_NUMERIC_LIT ?

In the end I was able to build the plugin but I'm having trouble to test it. I deactivated Qt python plugin and enabled the uaiso, setup (in my case) python paths in Options but so far does not seem it is running - unless I missed something.
Is it suppose to work in any file opened in Creator or should a start a new project?

**Comment by ltcmelo** [comment]
Sorry for the error. The correct should indeed be END_NUM_LIT, I just pushed a fix to Uaiso. Thanks for noticing.
Have you restarted Qt Creator after disabling the builtin Python stuff and enabling the Uaiso in the plugins tab? It should work for any file with the .py extension.

**Comment by ltcmelo** [comment]
Closing this one, since the plugin issue is being discussed in another thread.
