### ISSUE TITLE
Could you provide the binary for Mac?

### ISSUE THREAD

**Issue by tienhv** [ltcmelo/uaiso-plugins#6]
Hi,
Thank so much for your hard work on this project. Could you provide the binary so I can try it in action?

**Comment by ltcmelo** [comment]
Thanks Van Tien. This project is just a plugin for the Qt Creator that wraps the functionality of the [uaiso](https://github.com/ltcmelo/uaiso) project. But the uaiso is in early development stage and I don't have the infrastructure to provide reliable binaries. To test it with Qt Creator you need all of Qt, Qt Creator, Uaiso, and dependencies compiled together with the same compiler/options/platform. Nevertheless, if you need help building everything, I'd glad to assist you, feel free to drop me an email.
