### ISSUE TITLE
Install not working in Qt Creator 4.2

### ISSUE THREAD

**Issue by GrierPhillips** [ltcmelo/uaiso-plugins#7]
Following your directions for installation I downloaded the uaisoeditor directory and copied it into the plugins folder of my Qt Creator.app. The full path is ~/Qt/Qt Creator.app/Contents/Plugins.

Unfortunately this did not load the plugin. Is there something else I need to be doing for the plugin to work. I noticed all of the files in the plugins directory are .dylib. Does the package need to be built as a dylib file?

**Comment by ltcmelo** [comment]
Yes, and it must be built with the same compiler/options as Qt/Qt Creator. Otherwise, you might run into binary compatibility issues.

**Comment by GrierPhillips** [comment]
Ok. Never built a .dylib before I'm assuming I would use clang, but do you happen to have specific directions?

**Comment by ltcmelo** [comment]
You can uses Uaiso's own cmake file, just enable the SHARED_LIB option.
